CREATE TABLE IF NOT EXISTS provider_profiles (
  user_id INT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  bio TEXT,
  profile_pic_url VARCHAR(255),
  year_of_birth INT,
  place_of_birth VARCHAR(30),
  gender CHAR(1),
  languages JSON,
  first_name VARCHAR(22),
  last_name VARCHAR(25),
  suffix VARCHAR(3),
  license_number VARCHAR(9),
  license_state VARCHAR(2) DEFAULT 'TX',
  license_issued_date DATE,
  license_expiration_date DATE,
  registration_status VARCHAR(3),
  registration_date DATE,
  method_of_licensure CHAR(1),
  medical_school VARCHAR(67),
  graduation_year INT,
  degree_type VARCHAR(2),
  primary_specialty VARCHAR(30),
  secondary_specialty VARCHAR(30),
  board_certifications JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  working_plan JSON,
  timezone VARCHAR(50) DEFAULT 'America/Chicago',
  
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_username (username),
  INDEX idx_license (license_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;